[project]
name = "rosalind"
version = "0.1.0"
description = "Solutions for problems at rosalind.info"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "typer>=0.20.0",
]

[dependency-groups]
dev = [
    "black>=25.11.0",
    "pytest>=9.0.1",
]
